/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 * @param error 
 * @param message 
 * @param status 
 */


data class MainAPIResponse (

    @Json(name = "data")
    val `data`: kotlin.Any? = null,

    @Json(name = "error")
    val error: kotlin.Boolean? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.Int? = null

)

