/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package whatsapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param file Video file
 */


data class InstancesInstanceKeySendVideoPostRequest (

    /* Video file */
    @Json(name = "file")
    val file: java.io.File

)

