/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package whatsapi.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param directPath 
 * @param fileEncSha256 
 * @param fileLength 
 * @param fileSha256 
 * @param mediaKey 
 * @param mimeType 
 * @param url 
 */


data class StructsFileUpload (

    @Json(name = "direct_path")
    val directPath: kotlin.String,

    @Json(name = "file_enc_sha256")
    val fileEncSha256: kotlin.collections.List<kotlin.Int>,

    @Json(name = "file_length")
    val fileLength: kotlin.Int,

    @Json(name = "file_sha256")
    val fileSha256: kotlin.collections.List<kotlin.Int>,

    @Json(name = "media_key")
    val mediaKey: kotlin.collections.List<kotlin.Int>,

    @Json(name = "mime_type")
    val mimeType: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String

)

