/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package whatsapi.models

import whatsapi.models.StructsListItem

import com.squareup.moshi.Json

/**
 * 
 *
 * @param rows 
 * @param title 
 */


data class StructsListSection (

    @Json(name = "rows")
    val rows: kotlin.collections.List<StructsListItem>,

    @Json(name = "title")
    val title: kotlin.String

)

