/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param instanceKey 
 * @param webhookUrl 
 */


data class CreateInstancePayload (

    @Json(name = "instance_key")
    val instanceKey: kotlin.String? = null,

    @Json(name = "webhook_url")
    val webhookUrl: kotlin.String? = null

)

