/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package models

import models.LocationMessagePayloadLocation

import com.squareup.moshi.Json

/**
 * 
 *
 * @param location 
 * @param to 
 * @param url 
 */


data class LocationMessagePayload (

    @Json(name = "location")
    val location: LocationMessagePayloadLocation,

    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String? = null

)

