/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param buttonId 
 * @param buttonText 
 */


data class ReplyButton (

    @Json(name = "button_id")
    val buttonId: kotlin.String? = null,

    @Json(name = "button_text")
    val buttonText: kotlin.String? = null

)

