/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param latitude 
 * @param longitude 
 * @param name 
 * @param address 
 */


data class StructsLocationMessagePayloadLocation (

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "address")
    val address: kotlin.String? = null

)

