/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param participants 
 */


data class StructsGroupUpdateParticipantsPayload (

    @Json(name = "participants")
    val participants: kotlin.collections.List<kotlin.String>? = null

)

