/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param groupName 
 * @param participants 
 */


data class StructsGroupCreatePayload (

    @Json(name = "group_name")
    val groupName: kotlin.String? = null,

    @Json(name = "participants")
    val participants: kotlin.collections.List<kotlin.String>? = null

)

