/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param text 
 * @param to 
 */


data class TextMessage (

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "to")
    val to: kotlin.String

)

